require("em0ral.plugins-setup")
require("em0ral.core.options")
require("em0ral.core.keymaps")
require("em0ral.core.colorscheme")
require("em0ral.plugins.comment")
require("em0ral.plugins.nvim-tree")
require("em0ral.plugins.lualine")
require("em0ral.plugins.telescope")
require("em0ral.plugins.nvim-cmp")
require("em0ral.plugins.lsp.mason")
require("em0ral.plugins.lsp.lspsaga")
require("em0ral.plugins.lsp.lspconfig")

